#!/bin/bash

INITIAL_SUPPLY=${INITIAL_SUPPLY:-100000000000000000000000000000}
DELTA_SUPPLY=${DELTA_SUPPLY:-${INITIAL_SUPPLY}}
OPEN_UNSIGNED_FAUCET=${OPEN_UNSIGNED_FAUCET:-false}
KEY_OF_GAMETE=${KEY_OF_GAMETE:-missing}
CHAIN_ID=${CHAIN_ID:-missing}
MAX_GAS_PER_VIEW=${MAX_GAS_PER_VIEW:-10000000}
OBLIVION=${OBLIVION:-250000}
INFLATION=${INFLATION:-100000}
INITIAL_GAS_PRICE=${INITIAL_GAS_PRICE:-100}
TIMEOUT_COMMIT=${TIMEOUT_COMMIT:-5}
TOTAL_VALIDATION_POWER=${TOTAL_VALIDATION_POWER:-1000000}
BUYER_SURCHARGE=${BUYER_SURCHARGE:-50000000}
PERCENT_STAKED=${PERCENT_STAKED:-75000000}
SLASHING_FOR_MISBEHAVING=${SLASHING_FOR_MISBEHAVING:-1000000}
SLASHING_FOR_NOT_BEHAVING=${SLASHING_FOR_NOT_BEHAVING:-500000}

echo
echo "Starting a Tendermint node as the single initial validator of a brand new blockchain"
echo "  CHAIN_ID=$CHAIN_ID"
echo "  INITIAL_SUPPLY=$INITIAL_SUPPLY"
echo "  DELTA_SUPPLY=$DELTA_SUPPLY"
echo "  KEY_OF_GAMETE=$KEY_OF_GAMETE"
echo "  INITIAL_GAS_PRICE=$INITIAL_GAS_PRICE"
echo "  OPEN_UNSIGNED_FAUCET=$OPEN_UNSIGNED_FAUCET"
echo "  MAX_GAS_PER_VIEW=$MAX_GAS_PER_VIEW"
echo "  OBLIVION=$OBLIVION"
echo "  INFLATION=$INFLATION"
echo "  TIMEOUT_COMMIT=$TIMEOUT_COMMIT"
echo "  TOTAL_VALIDATION_POWER=$TOTAL_VALIDATION_POWER"
echo "  BUYER_SURCHARGE=$BUYER_SURCHARGE"
echo "  PERCENT_STAKED=$PERCENT_STAKED"
echo "  SLASHING_FOR_MISBEHAVING=$SLASHING_FOR_MISBEHAVING"
echo "  SLASHING_FOR_NOT_BEHAVING=$SLASHING_FOR_NOT_BEHAVING"

# create the key pair of the validator account
VALIDATOR_ACCOUNT_CREATION=$(moka create-key --password-of-new-key= --interactive=false --private-key)
LINE3=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '3!d')
PUBLIC_KEY_BASE64=${LINE3:19}
echo "  PUBLIC KEY OF THIS NODE AS VALIDATOR=$PUBLIC_KEY_BASE64"
LINE6=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '6!d')
CONCATENATED_KEYS_BASE64=${LINE6:40}
LINE7=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '7!d')
TENDERMINT_ADDRESS=${LINE7:25}
echo "  TENDERMINT ADDRESS OF THIS NODE AS VALIDATOR=$TENDERMINT_ADDRESS"
VALIDATOR_ACCOUNT_CREATION=

# create an initial Tendermint configuration, that later will be modified for our needs
tendermint testnet --v 1 --o . >> /dev/null

# we replace the validator's key used by Tendermint with that created above
echo "{
  \"address\": \"${TENDERMINT_ADDRESS}\",
  \"pub_key\": {
    \"type\": \"tendermint/PubKeyEd25519\",
    \"value\": \"${PUBLIC_KEY_BASE64}\"
  },
  \"priv_key\": {
    \"type\": \"tendermint/PrivKeyEd25519\",
    \"value\": \"${CONCATENATED_KEYS_BASE64}\"
  }
}" > node0/config/priv_validator_key.json

CONCATENATED_KEYS_BASE64=

# set the id of the validator also in the genesis file
sed -i '/"address": /s/".*"/"address": "'$TENDERMINT_ADDRESS'"/' node0/config/genesis.json

# set the public key of the validator also in the genesis file:
# we must escape / into \/ otherwise sed complains
PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64//\//\\\/}
sed -i '/"value": /s/".*"/"value": "'${PUBLIC_KEY_BASE64}'"/' node0/config/genesis.json

# set the power of the only initial validator in the genesis file: it holds all validation power initially
sed -i '/"power": /s/".*"/"power": "'${TOTAL_VALIDATION_POWER}'"/' node0/config/genesis.json

# set the chain id as requested
sed -i '/"chain_id": /s/".*"/"chain_id": "'$CHAIN_ID'"/' node0/config/genesis.json

# disable the creation of empty blocks
sed -i "s/create_empty_blocks = true/create_empty_blocks = false/g" node0/config/config.toml

# set the timeout for commits
sed -i '/timeout_commit = /s/".*"/"'${TIMEOUT_COMMIT}s'"/' node0/config/config.toml

# invoke moka in a way that deletes the tendermint configuration that was initially
# created into node0, so that we do not leave garbage around;
# in any case, it has been copied inside the chain directory
moka init-tendermint ${INITIAL_SUPPLY} --delta-supply=${DELTA_SUPPLY} --interactive=false --open-unsigned-faucet=${OPEN_UNSIGNED_FAUCET} --key-of-gamete=${KEY_OF_GAMETE} --takamaka-code /modules/explicit/io-takamaka-code-TAKAMAKA-VERSION.jar --tendermint-config=node0 --delete-tendermint-config --bind-validators --max-gas-per-view ${MAX_GAS_PER_VIEW} --oblivion ${OBLIVION} --inflation ${INFLATION} --initial-gas-price ${INITIAL_GAS_PRICE} --percent-staked ${PERCENT_STAKED} --buyer-surcharge ${BUYER_SURCHARGE} --slashing-for-misbehaving ${SLASHING_FOR_MISBEHAVING} --slashing-for-not-behaving ${SLASHING_FOR_NOT_BEHAVING}