#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Starting an already configured node of a blockchain, whose configuration has been created with config-go or with config-init and then init.${NC}"

moka-print-logs nodes tendermint resume \
    --tendermint-config=hotmoka_tendermint/tendermint_config \
	--local-config=hotmoka_tendermint/local_config.toml
