#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
BOLD_CYAN='\033[1;36m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}This container manages Hotmoka nodes using Tendermint as byzantine consensus engine.${NC}"
echo
echo "This container could be run with two volumes, one for the chain directory and another for the configuration"
echo "directory of the node, and mapping all ports that could be used by Hotmoka or Tendermint:"
echo -e "  ${BOLD_CYAN}docker run -it -p 8001:8001 -p 26656:26656 -v chain:/home/hotmoka/chain -v hotmoka_tendermint:/home/hotmoka/hotmoka_tendermint hotmoka/tendermint-node:VERSION /bin/bash${NC}"
echo
echo "The following commands and options are available inside the container:"
echo
echo -e "* ${RED}info:${NC}         print this information message"
echo
echo -e "* ${RED}config-init:${NC}  create the configuration directory of the first node of a brand new blockchain"
echo -e "    ${BLUE}ALLOWS_UNSIGNED_FAUCET:${NC} true if the unsigned faucet must be opened"
echo -e "    ${BLUE}CHAIN_ID:${NC} the chain identifier of the blockchain"
echo -e "    ${BLUE}INITIAL_SUPPLY:${NC} the initial supply of coins of the blockchain"
echo -e "    ${BLUE}FINAL_SUPPLY:${NC} the final supply of coins of the blockchain"
echo -e "    ${BLUE}PUBLIC_KEY_OF_GAMETE:${NC} the Base64-encoded public key of the gamete of the blockchain"
echo -e "    ${BLUE}TARGET_BLOCK_CREATION_TIME:${NC} the milliseconds between two successive blocks"
echo -e "    ${BLUE}TOTAL_VALIDATION_POWER:${NC} the total units of validation power, initially owned by the first validator account"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e PUBLIC_KEY_OF_GAMETE=\"ZgEyMfo89coBtA2i7IMnLzZleFzWLcfDan3dMVDDb38=\" hotmoka/tendermint-node:VERSION config-init${NC}"
echo
echo -e "* ${RED}config-start:${NC} create the configuration directory of a new node of an existing blockchain"
echo -e "    ${BLUE}HOTMOKA_PUBLIC_SERVICE_URI${NC}: the URI of an already existing node of the blockchain"
echo -e "    ${BLUE}TARGET_BLOCK_CREATION_TIME${NC}: the milliseconds between two successive blocks"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e HOTMOKA_PUBLIC_SERVICE_URI=ws://panarea.hotmoka.io:8002 hotmoka/tendermint-node:VERSION config-start${NC}"
echo
echo -e "* ${RED}init:${NC}         create a node for a brand new blockchain, whose configuration has been created with config-init"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -dit -p 8001:8001 -p 26656:26656 -v chain:/home/hotmoka/chain -v hotmoka_tendermint:/home/hotmoka/hotmoka_tendermint hotmoka/tendermint-node:VERSION init${NC}"
echo
echo -e "* ${RED}start:${NC}        create a node that connects to an already existing node of a blockchain, whose configuration has been created with config-start"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -dit -p 8001:8001 -p 26656:26656 -v chain:/home/hotmoka/chain -v hotmoka_tendermint:/home/hotmoka/hotmoka_tendermint hotmoka/tendermint-node:VERSION start${NC}"
echo
echo -e "* ${RED}resume:${NC}       resume a node whose container was previously turned off"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -dit -p 8001:8001 -p 26656:26656 -v chain:/home/hotmoka/chain -v hotmoka_tendermint:/home/hotmoka/hotmoka_tendermint hotmoka/tendermint-node:VERSION resume${NC}"
echo
echo -e "${RED}init/start/resume${NC} assume that the configuration directory of the node is available in the same directory where they are executed."