#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Resuming an already existing node.${NC}"

moka-print-logs nodes tendermint resume \
	--local-config=hotmoka_tendermint/local_config.toml
