#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Starting a Hotmoka node based on Tendermint that waits for blocks from peers before starting mining.${NC}"

moka-print-logs nodes tendermint start \
	--yes \
	--tendermint-config=hotmoka_tendermint/tendermint_config \
	--local-config=hotmoka_tendermint/local_config.toml