package io.hotmoka.network.models.responses;

import io.hotmoka.beans.responses.MethodCallTransactionExceptionResponse;
import io.hotmoka.network.models.updates.UpdateModel;
import io.hotmoka.network.models.values.StorageReferenceModel;

import java.util.List;
import java.util.stream.Collectors;

public class MethodCallTransactionExceptionResponseModel extends MethodCallTransactionResponseModel {

    /**
     * The events generated by this transaction.
     */
    private final List<StorageReferenceModel> events;

    /**
     * The fully-qualified class name of the cause exception.
     */
    public final String classNameOfCause;

    /**
     * The message of the cause exception.
     */
    public final String messageOfCause;

    /**
     * The program point where the cause exception occurred.
     */
    public final String where;


    public MethodCallTransactionExceptionResponseModel(MethodCallTransactionExceptionResponse response) {
        super(response);

        this.events = response.getEvents().map(StorageReferenceModel::new).collect(Collectors.toList());
        this.classNameOfCause = response.classNameOfCause;
        this.messageOfCause = response.messageOfCause;
        this.where = response.where;
    }

    public MethodCallTransactionExceptionResponse toBean() {
        return new MethodCallTransactionExceptionResponse(
        	classNameOfCause,
        	messageOfCause,
        	where,
            updates.stream().map(UpdateModel::toBean),
            events.stream().map(StorageReferenceModel::toBean),
            gasConsumedForCPU,
            gasConsumedForRAM,
            gasConsumedForStorage
        );
    }
}
