package io.hotmoka.network.models.responses;

import io.hotmoka.beans.annotations.Immutable;
import io.hotmoka.beans.responses.VoidMethodCallTransactionSuccessfulResponse;
import io.hotmoka.network.models.updates.UpdateModel;
import io.hotmoka.network.models.values.StorageReferenceModel;

import java.util.List;
import java.util.stream.Collectors;

@Immutable
public class VoidMethodCallTransactionSuccessfulResponseModel extends MethodCallTransactionResponseModel {

    /**
     * The events generated by this transaction.
     */
    private final List<StorageReferenceModel> events;


    public VoidMethodCallTransactionSuccessfulResponseModel(VoidMethodCallTransactionSuccessfulResponse response) {
        super(response);

        this.events = response.getEvents().map(StorageReferenceModel::new).collect(Collectors.toList());
    }

    public VoidMethodCallTransactionSuccessfulResponse toBean() {
        return new VoidMethodCallTransactionSuccessfulResponse(
                this.updates.stream().map(UpdateModel::toBean).collect(Collectors.toSet()).stream(),
                this.events.stream().map(StorageReferenceModel::toBean).collect(Collectors.toList()).stream(),
                this.gasConsumedForCPU,
                this.gasConsumedForRAM,
                this.gasConsumedForStorage
        );
    }
}
