package io.hotmoka.network.models.responses;

import java.math.BigInteger;
import java.util.List;
import java.util.stream.Collectors;

import io.hotmoka.beans.responses.VoidMethodCallTransactionSuccessfulResponse;
import io.hotmoka.network.models.updates.UpdateModel;
import io.hotmoka.network.models.values.StorageReferenceModel;

public class VoidMethodCallTransactionSuccessfulResponseModel extends MethodCallTransactionResponseModel {

    /**
     * The events generated by this transaction.
     */
    private List<StorageReferenceModel> events;

    public VoidMethodCallTransactionSuccessfulResponseModel(VoidMethodCallTransactionSuccessfulResponse response) {
        super(response);

        this.events = response.getEvents().map(StorageReferenceModel::new).collect(Collectors.toList());
    }

    public VoidMethodCallTransactionSuccessfulResponseModel() {}

    public VoidMethodCallTransactionSuccessfulResponse toBean() {
        return new VoidMethodCallTransactionSuccessfulResponse(
        	updates.stream().map(UpdateModel::toBean),
        	events.stream().map(StorageReferenceModel::toBean),
        	new BigInteger(gasConsumedForCPU),
        	new BigInteger(gasConsumedForRAM),
        	new BigInteger(gasConsumedForStorage)
        );
    }
}
