/*
Copyright 2021 Fausto Spoto

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package io.hotmoka.node.internal.responses;

import java.io.IOException;
import java.math.BigInteger;
import java.util.Arrays;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import io.hotmoka.annotations.Immutable;
import io.hotmoka.exceptions.ExceptionSupplier;
import io.hotmoka.exceptions.Objects;
import io.hotmoka.marshalling.api.MarshallingContext;
import io.hotmoka.marshalling.api.UnmarshallingContext;
import io.hotmoka.node.Updates;
import io.hotmoka.node.api.responses.ConstructorCallTransactionSuccessfulResponse;
import io.hotmoka.node.api.updates.Update;
import io.hotmoka.node.api.values.StorageReference;
import io.hotmoka.node.internal.json.TransactionResponseJson;
import io.hotmoka.node.internal.values.StorageReferenceImpl;
import io.hotmoka.websockets.beans.api.InconsistentJsonException;

/**
 * Implementation of a response for a successful transaction that calls a constructor to instantiate an object in the store
 * of the node. The constructor has been called without problems and without generating exceptions.
 */
@Immutable
public class ConstructorCallTransactionSuccessfulResponseImpl extends CodeExecutionTransactionResponseImpl implements ConstructorCallTransactionSuccessfulResponse {
	final static byte SELECTOR = 6;
	final static byte SELECTOR_NO_EVENTS = 13;

	/**
	 * The events generated by this transaction.
	 */
	private final StorageReference[] events;

	/**
	 * The object that has been created by the constructor call.
	 */
	private final StorageReference newObject;

	/**
	 * Builds the transaction response.
	 * 
	 * @param newObject the object that has been successfully created
	 * @param updates the updates resulting from the execution of the transaction
	 * @param events the events resulting from the execution of the transaction
	 * @param gasConsumedForCPU the amount of gas consumed by the transaction for CPU execution
	 * @param gasConsumedForRAM the amount of gas consumed by the transaction for RAM allocation
	 * @param gasConsumedForStorage the amount of gas consumed by the transaction for storage consumption
	 */
	public ConstructorCallTransactionSuccessfulResponseImpl(StorageReference newObject, Stream<Update> updates, Stream<StorageReference> events, BigInteger gasConsumedForCPU, BigInteger gasConsumedForRAM, BigInteger gasConsumedForStorage) {
		this(updates.toArray(Update[]::new), gasConsumedForCPU, gasConsumedForRAM, gasConsumedForStorage, newObject, events.toArray(StorageReference[]::new), IllegalArgumentException::new);
	}

	/**
	 * Unmarshals a response from the given stream.
	 * The selector of the response has been already processed.
	 * 
	 * @param context the unmarshalling context
	 * @param selector the selector
	 * @throws IOException if the response could not be unmarshalled
	 */
	public ConstructorCallTransactionSuccessfulResponseImpl(UnmarshallingContext context, byte selector) throws IOException {
		this(
			context.readLengthAndArray(Updates::from, Update[]::new),
			context.readBigInteger(),
			context.readBigInteger(),
			context.readBigInteger(),
			StorageReferenceImpl.fromWithoutSelector(context),
			unmarshalEvents(context, selector),
			IOException::new
		);
	}

	/**
	 * Creates a response from the given JSON representation.
	 * 
	 * @param json the JSON representation
	 * @throws InconsistentJsonException if {@code json} is inconsistent
	 */
	public ConstructorCallTransactionSuccessfulResponseImpl(TransactionResponseJson json) throws InconsistentJsonException {
		this(
			unmapUpdates(json),
			json.getGasConsumedForCPU(),
			json.getGasConsumedForRAM(),
			json.getGasConsumedForStorage(),
			unmapIntoStorageReference(json.getNewObject()),
			unmapEvents(json),
			InconsistentJsonException::new
		);
	}

	/**
	 * Builds the transaction response.
	 * 
	 * @param <E> the type of the exception thrown if some argument is illegal
	 * @param updates the updates resulting from the execution of the transaction
	 * @param gasConsumedForCPU the amount of gas consumed by the transaction for CPU execution
	 * @param gasConsumedForRAM the amount of gas consumed by the transaction for RAM allocation
	 * @param gasConsumedForStorage the amount of gas consumed by the transaction for storage consumption
	 * @param newObject the object that has been successfully created
	 * @param events the events resulting from the execution of the transaction
	 * @param onIllegalArgs the creator of the exception thrown if some argument is illegal
	 * @throws E if some argument is illegal
	 */
	private <E extends Exception> ConstructorCallTransactionSuccessfulResponseImpl(Update[] updates, BigInteger gasConsumedForCPU, BigInteger gasConsumedForRAM, BigInteger gasConsumedForStorage, StorageReference newObject, StorageReference[] events, ExceptionSupplier<? extends E> onIllegalArgs) throws E {
		super(updates, gasConsumedForCPU, gasConsumedForRAM, gasConsumedForStorage, IllegalArgumentException::new);

		this.newObject = Objects.requireNonNull(newObject, "newObject cannot be null", onIllegalArgs);

		this.events = Objects.requireNonNull(events, "events cannot be null", onIllegalArgs);
		for (var event: events)
			Objects.requireNonNull(event, "events cannot hold null elements", onIllegalArgs);

	}

	@Override
	public String toString() {
        return super.toString() + "\n"
       		+ "  new object: " + newObject + "\n"
        	+ "  events:\n" + getEvents().map(StorageReference::toString).collect(Collectors.joining("\n    ", "    ", ""));
	}

	@Override
	public final Stream<StorageReference> getEvents() {
		return Stream.of(events);
	}

	@Override
	public final boolean hasEvents() {
		return events.length > 0;
	}

	/**
	 * Yields the reference to the object that has been created.
	 * 
	 * @return the reference
	 */
	public final StorageReference getNewObject() {
		return newObject;
	}

	@Override
	public boolean equals(Object other) {
		return other instanceof ConstructorCallTransactionSuccessfulResponse cctsr && super.equals(other)
			&& Arrays.equals(events, cctsr.getEvents().toArray(StorageReference[]::new)) && newObject.equals(cctsr.getNewObject());
	}

	@Override
	public int hashCode() {
		return super.hashCode() ^ Arrays.hashCode(events) ^ newObject.hashCode();
	}

	@Override
	public void into(MarshallingContext context) throws IOException {
		context.writeByte(events.length == 0 ? SELECTOR_NO_EVENTS : SELECTOR);
		super.into(context);
		newObject.intoWithoutSelector(context);
		if (events.length > 0)
			intoArrayWithoutSelector(events, context);
	}

	private final static StorageReference[] NO_REFERENCES = new StorageReference[0];

	private static StorageReference[] unmarshalEvents(UnmarshallingContext context, byte selector) throws IOException {
		if (selector == SELECTOR)
			return context.readLengthAndArray(StorageReferenceImpl::fromWithoutSelector, StorageReference[]::new);
		else if (selector == SELECTOR_NO_EVENTS)
			return NO_REFERENCES;
		else
			throw new IOException("Unexpected response selector: " + selector);
	}
}