#!/bin/bash

CHAIN_ID=${CHAIN_ID:-""}
OPEN_UNSIGNED_FAUCET=${OPEN_UNSIGNED_FAUCET:-false}
HOTMOKA_NODE_DIR=${HOTMOKA_NODE_DIR:-"hotmoka_mokamint_node"}
PUBLIC_KEY_OF_GAMETE=${PUBLIC_KEY_OF_GAMETE:-""}
TARGET_BLOCK_CREATION_TIME=${TARGET_BLOCK_CREATION_TIME:-10000}

echo
echo "Starting a Mokamint node as the single initial node of a brand new blockchain"
echo "  CHAIN_ID=$CHAIN_ID"
echo "  OPEN_UNSIGNED_FAUCET=$OPEN_UNSIGNED_FAUCET"
echo "  PUBLIC_KEY_OF_GAMETE=$PUBLIC_KEY_OF_GAMETE"
echo "  TARGET_BLOCK_CREATION_TIME=$TARGET_BLOCK_CREATION_TIME"

moka nodes mokamint init \
	modules/explicit_or_automatic/io-takamaka-code-1.4.1.jar \
	${HOTMOKA_NODE_DIR}/plot.plot \
	${HOTMOKA_NODE_DIR}/node.pem \
	${HOTMOKA_NODE_DIR}/miner.pem \
	--open-unsigned-faucet=${OPEN_UNSIGNED_FAUCET} \
	--yes \
	--mokamint-config=${HOTMOKA_NODE_DIR}/mokamint_config.toml \
	--consensus-config=${HOTMOKA_NODE_DIR}/consensus_config.toml \
	--local-config=${HOTMOKA_NODE_DIR}/local_config.toml