#!/bin/bash

# This script creates the configuration directory of a Hotmoka node, for starting a node
# of an already existing blockchain. The configuration directory will have the following structure:
#
# miner.pem
# node.pem
# plot.plot
# mokamint_config.toml
# local_config.toml
#
# where:
# 1) miner.pem and node.pem are key pairs with empty password
# 2) plot.plot uses node.pem as key for signing the blocks, miner.pem as key for signing the deadlines and the chain identifier in mokamint_config.toml
# 3) options not explicitly reported in the three toml configuration files hold, implicitly, default values

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

MOKAMINT_PUBLIC_SERVICE_URI=${MOKAMINT_PUBLIC_SERVICE_URI:-ws://panarea.hotmoka.io:8030}
PLOT_SIZE=${PLOT_SIZE:-1000}

echo -e "${BOLD_GREEN}I will use the following parameters for the creation of the configuration directory of a Hotmoka node using Mokamint as proof of space consensus engine:${NC}"
echo
echo -e " ${BLUE}MOKAMINT_PUBLIC_SERVICE_URI${NC}=${RED}$MOKAMINT_PUBLIC_SERVICE_URI${NC}"
echo -e "                   ${BLUE}PLOT_SIZE${NC}=${RED}$PLOT_SIZE${NC}"
echo

echo -n "Cleaning the directory hotmoka_mokamint... "
rm -rf hotmoka_mokamint/*
echo -e "${RED}done${NC}"

echo -n "Creating the node.pem key pair for signing the blocks... "
PUBLIC_KEY_NODE_BASE58=$(moka keys create --output-dir=hotmoka_mokamint --name=node.pem --json | python3 -c "import sys, json; print(json.load(sys.stdin)['publicKeyBase58'])")
echo -e "${RED}done${NC}"

echo -n "Creating the miner.pem key pair for signing the deadlines... "
PUBLIC_KEY_MINER_BASE58=$(moka keys create --output-dir=hotmoka_mokamint --name=miner.pem --json | python3 -c "import sys, json; print(json.load(sys.stdin)['publicKeyBase58'])")
echo -e "${RED}done${NC}"

echo -n "Creating the local Hotmoka node configuration file... "
touch hotmoka_mokamint/local_config.toml
echo -e "${RED}done${NC}"

echo -n "Cloning the Mokamint configuration file from ${MOKAMINT_PUBLIC_SERVICE_URI}... "
# we need the chain id of the Mokamint network in order to create the plot later
CHAIN_ID=$(mokamint-node config show --uri $MOKAMINT_PUBLIC_SERVICE_URI --json | python3 -c "import sys, json; print(json.load(sys.stdin)['chainId'])")
mokamint-node config show --uri $MOKAMINT_PUBLIC_SERVICE_URI > hotmoka_mokamint/mokamint_config.toml
echo -e "${RED}done${NC}"

echo "Creating a plot file for the miner, containing ${PLOT_SIZE} nonces, for the chain id \"${CHAIN_ID}\"..."
mokamint-plotter create hotmoka_mokamint/plot.plot 0 $PLOT_SIZE "$CHAIN_ID" $PUBLIC_KEY_NODE_BASE58 $PUBLIC_KEY_MINER_BASE58
echo -e "${RED}done${NC}"

echo
echo "You can now copy the configuration directory into your local file system with:"
echo "  docker cp THIS_DOCKER_ID:/home/hotmoka/hotmoka_mokamint ."