#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Starting a Hotmoka node based on Mokamint in an already initialized blockchain.${NC}"
echo -e "  ${BLUE}VISIBLE_AS${NC}=${RED}${VISIBLE_AS}${NC}"

if [ ! -z "$VISIBLE_AS" ]
then
      VISIBLE_AS="--visible-as ${VISIBLE_AS}"
fi

moka-print-logs nodes mokamint resume \
	hotmoka_mokamint/plot.plot \
	hotmoka_mokamint/node.pem \
	--password-of-mokamint-node \
	--mokamint-config=hotmoka_mokamint/mokamint_config.toml \
	--local-config=hotmoka_mokamint/local_config.toml \
	$VISIBLE_AS