#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Initializing a node for a brand new blockchain, whose configuration has been created with config-new.${NC}"

moka-print-logs nodes mokamint init \
	/modules/explicit_or_automatic/io-takamaka-code-1.8.1.jar \
	hotmoka_mokamint/plot.plot \
	hotmoka_mokamint/node.pem \
	--yes \
	--exit-after-initialization \
	--password-of-mokamint-node \
	--mokamint-config=hotmoka_mokamint/mokamint_config.toml \
	--consensus-config=hotmoka_mokamint/consensus_config.toml \
	--local-config=hotmoka_mokamint/local_config.toml