#!/bin/bash

echo
echo "Resuming an already existing node"
echo "  VISIBLE_AS=${VISIBLE_AS}"

if [ ! -z "$VISIBLE_AS" ]
then
      VISIBLE_AS="--visible-as ${VISIBLE_AS}"
fi

moka nodes mokamint resume \
	hotmoka_mokamint/plot.plot \
	hotmoka_mokamint/node.pem \
	hotmoka_mokamint/miner.pem \
	--mokamint-config=hotmoka_mokamint/mokamint_config.toml \
	--local-config=hotmoka_mokamint/local_config.toml \
	$VISIBLE_AS