#!/bin/bash

MAX_GAS_PER_VIEW=${MAX_GAS_PER_VIEW:-10000000}

echo
echo "Starting a Mokamint node connected to the node at $NETWORK_URI:"
echo "  MAX_GAS_PER_VIEW=$MAX_GAS_PER_VIEW"

moka start-mokamint --interactive=true --mokamint-config=mokamint_node/mokamint_config.cfg --plot mokamint_node/plot.plot --keys mokamint_node/node.pem --keys-of-plot mokamint_node/miner.pem --max-gas-per-view ${MAX_GAS_PER_VIEW}