package io.hotmoka.network.responses;

import io.hotmoka.beans.responses.MethodCallTransactionExceptionResponse;
import io.hotmoka.network.updates.UpdateModel;
import io.hotmoka.network.values.StorageReferenceModel;

import java.math.BigInteger;
import java.util.List;
import java.util.stream.Collectors;

public class MethodCallTransactionExceptionResponseModel extends MethodCallTransactionResponseModel {

    /**
     * The events generated by this transaction.
     */
    private List<StorageReferenceModel> events;

    /**
     * The fully-qualified class name of the cause exception.
     */
    public String classNameOfCause;

    /**
     * The message of the cause exception.
     */
    public String messageOfCause;

    /**
     * The program point where the cause exception occurred.
     */
    public String where;

    public MethodCallTransactionExceptionResponseModel(MethodCallTransactionExceptionResponse response) {
        super(response);

        this.events = response.getEvents().map(StorageReferenceModel::new).collect(Collectors.toList());
        this.classNameOfCause = response.classNameOfCause;
        this.messageOfCause = response.messageOfCause;
        this.where = response.where;
    }

    public MethodCallTransactionExceptionResponseModel() {}

    public MethodCallTransactionExceptionResponse toBean() {
        return new MethodCallTransactionExceptionResponse(
        	classNameOfCause,
        	messageOfCause,
        	where,
        	selfCharged,
            updates.stream().map(UpdateModel::toBean),
            events.stream().map(StorageReferenceModel::toBean),
            new BigInteger(gasConsumedForCPU),
            new BigInteger(gasConsumedForRAM),
            new BigInteger(gasConsumedForStorage)
        );
    }
}
