#!/bin/bash

MAX_GAS_PER_VIEW=${MAX_GAS_PER_VIEW:-10000000}
TIMEOUT_COMMIT=${TIMEOUT_COMMIT:-5}
NETWORK_URI=${NETWORK_URI:=ws://panarea.hotmoka.io}
BASE_NETWORK_URI=$(echo $NETWORK_URI | sed s/":[0-9][0-9]*"/""/g | sed s/".*:\/\/"/""/g) # remove trailing port and protocol, if any

echo
echo "Starting a Tendermint node connected to the node at $NETWORK_URI:"
echo "  MAX_GAS_PER_VIEW=$MAX_GAS_PER_VIEW"
echo "  NETWORK_URI=$NETWORK_URI"
echo "  BASE_NETWORK_URI=$BASE_NETWORK_URI"
echo "  TIMEOUT_COMMIT=$TIMEOUT_COMMIT"
echo "  PUBLIC_KEY_BASE58=$PUBLIC_KEY_BASE58"
echo "  PUBLIC_KEY_BASE64=$PUBLIC_KEY_BASE64"
echo "  CONCATENATED_KEYS_BASE64=$CONCATENATED_KEYS_BASE64"
echo "  TENDERMINT_ADDRESS=$TENDERMINT_ADDRESS"

# extract information about the remote node, that are needed in order to prepare the Tendermint configuration of the local node
REMOTE_NODE_ID=$(moka node info --json --uri $NETWORK_URI | python3 -c "import sys, json; print(json.load(sys.stdin)['ID'])")
echo "  REMOTE_NODE_ID=$REMOTE_NODE_ID"
MANIFEST_TRANSACTION=$(moka node manifest address --json --uri $NETWORK_URI | python3 -c "import sys, json; print(json.load(sys.stdin)['transaction']['hash'])")
MANIFEST_PROGRESSIVE=$(moka node manifest address --json --uri $NETWORK_URI | python3 -c "import sys, json; print(json.load(sys.stdin)['progressive'])")
MANIFEST=$MANIFEST_TRANSACTION#$MANIFEST_PROGRESSIVE
echo "  MANIFEST=$MANIFEST"
CHAIN_ID=$(moka-no-logs call $MANIFEST getChainId --uri=$NETWORK_URI --print-costs=false --use-colors=false)
echo "  CHAIN_ID=$CHAIN_ID"
GENESIS_TIME=$(moka-no-logs call $MANIFEST getGenesisTime --uri=$NETWORK_URI --print-costs=false --use-colors=false)
echo "  GENESIS_TIME=$GENESIS_TIME"
INITIAL_VALIDATORS=$(moka-no-logs call $MANIFEST getInitialValidators --uri=$NETWORK_URI --print-costs=false --use-colors=false)
echo "  INITIAL_VALIDATORS=$INITIAL_VALIDATORS"
SHARES=$(moka-no-logs call $INITIAL_VALIDATORS getShares --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.dao.SharedEntityView)
echo "  SHARES=$SHARES"
NUM_INITIAL_VALIDATORS=$(moka-no-logs call $SHARES size --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.util.StorageMapView)
echo "  NUM_INITIAL_VALIDATORS=$NUM_INITIAL_VALIDATORS"

# extract information about each single initial validator, that goes into the Tendermint genesis file of the local node
for (( i=0; i<$NUM_INITIAL_VALIDATORS; i++ ))
do
	INITIAL_VALIDATOR=$(moka-no-logs call $SHARES select $i --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.util.StorageMapView)
	echo "    INITIAL_VALIDATOR #$i=$INITIAL_VALIDATOR"
	ID=$(moka-no-logs call $INITIAL_VALIDATOR id --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.governance.Validator)
	echo "    ID OF INITIAL_VALIDATOR #$i=$ID"
	PUBLIC_KEY=$(moka-no-logs call $INITIAL_VALIDATOR publicKey --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.lang.ExternallyOwnedAccount)
	echo "    PUBLIC KEY OF INITIAL_VALIDATOR #$i=$PUBLIC_KEY"
	POWER=$(moka-no-logs call $SHARES get $INITIAL_VALIDATOR --uri=$NETWORK_URI --print-costs=false --use-colors=false --class-of-receiver io.takamaka.code.util.StorageMapView)
	echo "    POWER OF INITIAL_VALIDATOR #$i=$POWER"
	
	# the JSON that goes into the Tendermint genesis file of the local node
	JSON='    {
      "address": "'$ID'",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "'$PUBLIC_KEY'"
      },
      "power": "'$POWER'",
      "name": "'$ID'"
    }'

	# merge the JSON of each single initial validator into a unique, comma-separated JSON string
    if [ -z "$INITIAL_VALIDATORS_JSON" ]
	then
        INITIAL_VALIDATORS_JSON=$JSON
	else
		INITIAL_VALIDATORS_JSON="${INITIAL_VALIDATORS_JSON}"$',\n'"${JSON}"
	fi
done

INITIAL_VALIDATORS_JSON=$'\n'"${INITIAL_VALIDATORS_JSON}"$'\n  '

echo "    INITIAL_VALIDATORS_JSON=$INITIAL_VALIDATORS_JSON"

# create the key pair of the validator account (used only if the node will ever become a validator);
# if the key pair was provided externally, the brand new key is just dropped
VALIDATOR_ACCOUNT_CREATION=$(moka create-key --password-of-new-key= --interactive=false --private-key)
LINE2=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '2!d')
PUBLIC_KEY_BASE58=${PUBLIC_KEY_BASE58:-${LINE2:19}}
LINE3=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '3!d')
PUBLIC_KEY_BASE64=${PUBLIC_KEY_BASE64:-${LINE3:19}}
echo "  PUBLIC KEY OF THIS NODE AS VALIDATOR=$PUBLIC_KEY_BASE64"
LINE6=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '6!d')
CONCATENATED_KEYS_BASE64=${CONCATENATED_KEYS_BASE64:-${LINE6:40}}
LINE7=$(echo "$VALIDATOR_ACCOUNT_CREATION"| sed '7!d')
TENDERMINT_ADDRESS=${TENDERMINT_ADDRESS:-${LINE7:25}}
echo "  TENDERMINT ADDRESS OF THIS NODE AS VALIDATOR=$TENDERMINT_ADDRESS"
echo "  KEY FILE OF THIS NODE AS VALIDATOR=${PUBLIC_KEY_BASE58}.pem"
VALIDATOR_ACCOUNT_CREATION=

# create an initial Tendermint configuration, that later will be modified for our needs
tendermint testnet --v 0 --n 1 --o . >> /dev/null

# we replace the validator's key used by Tendermint
# with that externally provided or with that created above
echo "{
  \"address\": \"${TENDERMINT_ADDRESS}\",
  \"pub_key\": {
    \"type\": \"tendermint/PubKeyEd25519\",
    \"value\": \"${PUBLIC_KEY_BASE64}\"
  },
  \"priv_key\": {
    \"type\": \"tendermint/PrivKeyEd25519\",
    \"value\": \"${CONCATENATED_KEYS_BASE64}\"
  }
}" > node0/config/priv_validator_key.json

# better to erase this secret information
CONCATENATED_KEYS_BASE64=

# set the chain id as in the remote node
sed -i '/"chain_id": /s/".*"/"chain_id": "'$CHAIN_ID'"/' node0/config/genesis.json

# set the genesis time as in the remote node
sed -i '/"genesis_time": /s/".*"/"genesis_time": "'$GENESIS_TIME'"/' node0/config/genesis.json

# set the initial validators as in the remote node
awk -v r=\"validators\":\ ["${INITIAL_VALIDATORS_JSON}"] '{gsub(/"validators": \[\]/,r)}1' node0/config/genesis.json > genesis.json
mv genesis.json node0/config/genesis.json

# disable the creation of empty blocks
sed -i "s/create_empty_blocks = true/create_empty_blocks = false/g" node0/config/config.toml

# set the timeout for commits
sed -i '/timeout_commit = /s/".*"/"'${TIMEOUT_COMMIT}s'"/' node0/config/config.toml

# set the remote node as persistent seed
echo "3"
sed -i '/persistent_peers =/s/".*"/"'$REMOTE_NODE_ID@$BASE_NETWORK_URI:26656'"/' node0/config/config.toml

# invoke moka in a way that deletes the tendermint configuration that was initially
# created into node0, so that we do not leave garbage around;
# in any case, it has been copied inside the chain directory
echo "4"
moka start-tendermint --interactive=false --tendermint-config=node0 --delete-tendermint-config --max-gas-per-view ${MAX_GAS_PER_VIEW}