#!/bin/bash

echo
echo "This container runs a node based on Mokamint."
echo "It understands the following commands and options"
echo "(use \"-e option=value\" to set options in docker):"
echo
echo "  help:   prints this help"
echo
echo "  init:   creates a node for a brand new blockchain"
echo "    OPEN_UNSIGNED_FAUCET: true if the gamete can be used as a free faucet of coins"
echo "      [default: false]"
echo
echo "  start:  creates a node that connects to an already existing node of a blockchain"
echo
echo "  resume: resumes a node whose container was previously turned off with \"docker stop\""
echo