#!/bin/bash

echo
echo "This container runs a node based on Mokamint."
echo "It understands the following commands and options"
echo "(use \"-e option=value\" to set options in docker):"
echo
echo "  help:   prints this help"
echo
echo "  init:   creates a node for a brand new blockchain"
echo "    DELTA_SUPPLY: the number of coins that can be minted during the life of the node,"
echo "                  as effect of inflation"
echo "      [default: equal to INITIAL_SUPPLY, hence the supply can double at most]"
echo "    KEY_OF_GAMETE: the Base58-encoded ed25519 public key of the gamete."
echo "                   Use \"moka create-key\" to generate one"
echo "      [required, no default]"
echo "    INFLATION: the inflation added to the validators' reward at each commit:"
echo "               0 means 0%, 1000000 means 1% (this can be negative)."
echo "               Use 0 to keep the total supply constant"
echo "      [default: 100000]"
echo "    INITIAL_GAS_PRICE: the initial price of a unit of gas"
echo "      [default: 100]"
echo "    INITIAL_SUPPLY: the initial balance of the node,"
echo "                    which goes to the gamete"
echo "      [default: 100000000000000000000000000000]"
echo "    MAX_GAS_PER_VIEW: the maximal gas limit allowed when running @View methods"
echo "      [default: 10000000]"
echo "    OBLIVION: a measure of how quickly the gas consumed by previous blocks"
echo "              is forgotten for the computation of the gas price:"
echo "              0 means never (ie, the gas price is constant), 1000000 means immediately."
echo "              Higher values make the gas price fluctuate more heavily"
echo "      [default: 250000]"
echo "    OPEN_UNSIGNED_FAUCET: true if the gamete can be used as a free faucet of coins"
echo "      [default: false]"
echo
echo "  start:  creates a node that connects to an already existing node of a blockchain"
echo "    MAX_GAS_PER_VIEW: the maximal gas limit allowed when running @View methods"
echo "      [default: 10000000]"
echo
echo "  resume: resumes a node whose container was previously turned off with \"docker stop\""
echo "    MAX_GAS_PER_VIEW: the maximal gas limit allowed when running @View methods"
echo "      [default: 10000000]"
echo