#!/bin/bash

MAX_GAS_PER_VIEW=${MAX_GAS_PER_VIEW:-1000000}
NETWORK_URL=${NETWORK_URL:=panarea.hotmoka.io}
BASE_NETWORK_URL=$(echo $NETWORK_URL | sed s/":.*"/""/g) # remove trailing port, if any

REMOTE_NODE_ID=$(curl --silent http://$NETWORK_URL/get/nodeID| python3 -c "import sys, json; print(json.load(sys.stdin)['ID'])")
MANIFEST_TRANSACTION=$(curl --silent http://$NETWORK_URL/get/manifest| python3 -c "import sys, json; print(json.load(sys.stdin)['transaction']['hash'])")
MANIFEST_PROGRESSIVE=$(curl --silent http://panarea.hotmoka.io:8080/get/manifest| python3 -c "import sys, json; print(json.load(sys.stdin)['progressive'])")
MANIFEST=$MANIFEST_TRANSACTION#$MANIFEST_PROGRESSIVE
CHAIN_ID=$(moka-no-logs call $MANIFEST getChainId --url=$NETWORK_URL --print-costs=false --use-colors=false)

echo
echo "Starting Hotmoka:"
echo "  MAX_GAS_PER_VIEW=$MAX_GAS_PER_VIEW"
echo "  NETWORK_URL=$NETWORK_URL"
echo "  BASE_NETWORK_URL=$BASE_NETWORK_URL"
echo "  REMOTE_NODE_ID=$REMOTE_NODE_ID"
echo "  MANIFEST=$MANIFEST"
echo "  CHAIN_ID=$CHAIN_ID"

tendermint testnet --v 0 --n 1 --o . >> /dev/null
# tendermint testnet creates a chain id of the form chain- followed
# by six characters: we replace it with the required chain id
sed -i "s/chain-....../$CHAIN_ID/g" node0/config/genesis.json

# we disable the creation of empty blocks
sed -i "s/create_empty_blocks = true/create_empty_blocks = false/g" node0/config/config.toml

# we set the remote node as persistent seed
sed -i '/persistent_peers =/s/".*"/\"'$REMOTE_NODE_ID@$BASE_NETWORK_URL:26656'\"/' node0/config/config.toml

# we delete the tendermint configuration that we have temporarily
# created into node0, so that we do not leave garbage around;
# in any case, it has been copied inside the chain directory
# moka start-tendermint --non-interactive --tendermint-config=node0 --delete-tendermint-config --max-gas-per-view ${MAX_GAS_PER_VIEW}
/bin/bash