#!/bin/bash

MAX_GAS_PER_VIEW=${MAX_GAS_PER_VIEW:-1000000}
NETWORK_URL=${NETWORK_URL:=panarea.hotmoka.io}

echo
echo "Starting Hotmoka:"
echo "  MAX_GAS_PER_VIEW=$MAX_GAS_PER_VIEW"

tendermint testnet --v 0 --n 1 --o . >> /dev/null
# tendermint testnet creates a chain id of the form chain- followed
# by six characters: we replace it with the required chain id
#sed -i "s/chain-....../$CHAIN_ID/g" node0/config/genesis.json
sed -i "s/create_empty_blocks = true/create_empty_blocks = false/g" node0/config/config.toml

# we delete the tendermint configuration that we have temporarily
# created into node0, so that we do not leave garbage around;
# in any case, it has been copied inside the chain directory
# moka start-tendermint --non-interactive --tendermint-config=node0 --delete-tendermint-config --max-gas-per-view ${MAX_GAS_PER_VIEW}
