package io.takamaka.code.engine.internal.transactions;

import java.util.NoSuchElementException;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;

import io.hotmoka.beans.GasCostModel;
import io.hotmoka.beans.TransactionRejectedException;
import io.hotmoka.beans.references.TransactionReference;
import io.hotmoka.nodes.Node;
import io.takamaka.code.engine.LRUCache;
import io.takamaka.code.engine.Store;
import io.takamaka.code.engine.internal.EngineClassLoader;
import io.takamaka.code.instrumentation.StandardGasCostModel;

/**
 * The methods of an abstract node that are only used inside this package.
 * By using this proxy class, we avoid to define them as public.
 */
public abstract class AbstractNodeProxyForTransactions<S extends Store> implements Node {

	/**
	 * The cache.
	 */
	private final LRUCache<TransactionReference, EngineClassLoader> cache;

	/**
	 * An executor for short background tasks.
	 */
	private final ExecutorService executor;

	/**
	 * The default gas model of the node.
	 */
	private final static GasCostModel defaultGasCostModel = new StandardGasCostModel();

	/**
	 * Builds a node.
	 */
	protected AbstractNodeProxyForTransactions() {
		this.cache = new LRUCache<>(100, 1000);
		this.executor = Executors.newCachedThreadPool();
	}

	/**
	 * Builds a clone of the given node.
	 * 
	 * @param parent the node to clone
	 */
	protected AbstractNodeProxyForTransactions(AbstractNodeProxyForTransactions<S> parent) {
		this.cache = parent.cache;
		this.executor = parent.executor;
	}

	@Override
	public void close() throws Exception {
		executor.shutdown();
		executor.awaitTermination(10, TimeUnit.SECONDS);
	}

	/**
	 * Yields the gas cost model of this node.
	 * 
	 * @return the default gas cost model. Subclasses may redefine
	 */
	public GasCostModel getGasCostModel() {
		return defaultGasCostModel;
	}

	/**
	 * Yields the response generated by the transaction with the given reference.
	 * 
	 * @param reference the reference of the transaction
	 * @return the response
	 * @throws TransactionRejectedException if there is a request for that transaction but it failed with this exception
	 * @throws NoSuchElementException if there is no request, and hence no response, with that reference
	 */
	protected final EngineClassLoader getCachedClassLoader(TransactionReference classpath) throws Exception {
		return cache.computeIfAbsent(classpath, this::mkClassLoader);
	}

	/**
	 * Creates a new class loader for the given class path.
	 * 
	 * @param classpath the class path
	 * @return the class loader
	 * @throws Exception if the class loader cannot be created
	 */
	protected abstract EngineClassLoader mkClassLoader(TransactionReference classpath) throws Exception;

	/**
	 * Runs the given task with the executor service of this node.
	 * 
	 * @param <T> the type of the result of the task
	 * @param task the task
	 * @return the value computed by the task
	 */
	protected final <T> Future<T> submit(Callable<T> task) {
		return executor.submit(task);
	}

	/**
	 * Runs the given task with the executor service of this node.
	 * 
	 * @param task the task
	 */
	protected final void submit(Runnable task) {
		executor.submit(task);
	}

	/**
	 * Clears the caches of this node.
	 */
	protected void invalidateCaches() {
		cache.clear();
	}
}