package io.takamaka.code.engine.internal.transactions;

import java.util.NoSuchElementException;

import io.hotmoka.beans.TransactionRejectedException;
import io.hotmoka.beans.references.TransactionReference;
import io.takamaka.code.engine.LRUCache;
import io.takamaka.code.engine.internal.EngineClassLoader;

/**
 * The methods of an abstract node that are only used inside this package.
 * By using this proxy class, we avoid to define them as public.
 */
public abstract class AbstractNodeProxyForTransactions {

	/**
	 * The cache.
	 */
	private final LRUCache<TransactionReference, EngineClassLoader> cache = new LRUCache<>(100, 1000);

	/**
	 * Yields the response generated by the transaction with the given reference.
	 * 
	 * @param reference the reference of the transaction
	 * @return the response
	 * @throws TransactionRejectedException if there is a request for that transaction but it failed with this exception
	 * @throws NoSuchElementException if there is no request, and hence no response, with that reference
	 */
	protected final EngineClassLoader getCachedClassLoader(TransactionReference classpath) throws Exception {
		return cache.computeIfAbsent(classpath, this::mkClassLoader);
	}

	/**
	 * Creates a new class loader for the given class path.
	 * 
	 * @param classpath the class path
	 * @return the class loader
	 * @throws Exception if the class loader cannot be created
	 */
	protected abstract EngineClassLoader mkClassLoader(TransactionReference classpath) throws Exception;

	/**
	 * Determines if this node is initialized, that is, a (possibly still uncommitted)
	 * initialization transaction has been run already on this node.
	 * 
	 * @return true if and only if that condition holds
	 */
	protected abstract boolean isInitialized();
}