import {CodeExecutionTransactionResponseModel} from "./CodeExecutionTransactionResponseModel";

export abstract class ConstructorCallTransactionResponseModel extends CodeExecutionTransactionResponseModel {}