name: Java-Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -Dmaven.javadoc.skip --file pom.xml
      - name: Tar moka
        run: tar -cvf moka.tar modules/* moka moka.bat; gzip moka.tar
      - name: Tar blue
        run: tar --transform='s/moka$/blue/' --transform='s/moka.bat$/blue.bat/' -cvf blue.tar modules/* moka moka.bat; gzip blue.tar
      - name: Upload moka
        uses: actions/upload-artifact@v4
        with:
          name: moka
          path: moka.tar.gz
        if: always()
      - name: Upload blue
        uses: actions/upload-artifact@v4
        with:
          name: blue
          path: blue.tar.gz
        if: always()
