name: Java-Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11.0.7
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.7'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package -Dmaven.javadoc.skip --file pom.xml
      - name: Tar files
        run: tar -cvf moka.tar modules/* moka moka.bat; gzip moka.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: moka
          path: moka.tar.gz
        if: always()
